USE REPORTE
GO

BULK INSERT DATOS.CLIENTES
FROM 'C:\Proyecto\TABLAS\DATOS_CLIENTES.csv'
WITH (
		FORMAT = 'csv',
		FIELDTERMINATOR = ';',
		CODEPAGE = '65001', --UTF-8
		FIRSTROW = 2
)
GO

BULK INSERT DATOS.EDAD
FROM 'C:\Proyecto\TABLAS\DATOS_EDAD.csv'
WITH (
		FORMAT = 'csv',
		FIELDTERMINATOR = ';',
		FIRSTROW = 2
)
GO

BULK INSERT TIPOS.CLIENTES
FROM 'C:\Proyecto\TABLAS\TIPOS_CLIENTES.csv'
WITH (
		FORMAT = 'csv',
		FIELDTERMINATOR = ';',
		FIRSTROW = 2
)
GO

BULK INSERT VENTAS.ALTA_CLIENTES
FROM 'C:\Proyecto\TABLAS\ALTA_CLIENTES.csv'
WITH (
		FORMAT = 'csv',
		FIELDTERMINATOR = ';',
		FIRSTROW = 2
)
GO