CREATE DATABASE REPORTE
GO

USE REPORTE
GO

CREATE SCHEMA VENTAS 
GO

CREATE SCHEMA TIPOS
GO

CREATE SCHEMA DATOS
GO

CREATE TABLE DATOS.CLIENTES(
	ID_CLIENTE INT PRIMARY KEY,
	NOMBRE_COMPLETO nvarchar(30),
)
GO

ALTER TABLE DATOS.CLIENTES
ALTER COLUMN NOMBRE_COMPLETO NVARCHAR(65)
GO

CREATE TABLE DATOS.EDAD(
	FECHA_NACIMIENTO DATE,
	EDAD INT,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE) REFERENCES DATOS.CLIENTES(ID_CLIENTE)
)
GO

CREATE TABLE TIPOS.CLIENTES(
	ID_TIPOS INT PRIMARY KEY NOT NULL,
	GRUPO_CLIENTES VARCHAR(5)
)
GO

CREATE TABLE VENTAS.ALTA_CLIENTES(
	DIRECCION NVARCHAR(60),
	CODIGO_TELEFONICO VARCHAR(4),
	TELEFONO VARCHAR (8),
	CORREO_ELECTRONICO NVARCHAR(50),
	FECHA_ALTA DATE,
	ID_CLIENTE INT,
	ID_TIPOS INT,
	FOREIGN KEY (ID_CLIENTE) REFERENCES DATOS.CLIENTES(ID_CLIENTE),
	FOREIGN KEY (ID_TIPOS) REFERENCES TIPOS.CLIENTES(ID_TIPOS)
)
GO